version: '3.3'

networks:
  proxy:
    driver: overlay
    # Created in admin-stack
    external: true


volumes:
  pg_data:
    driver_opts:
        type: none
        device: ${DATA_DIR}/postgres/data
        o: bind


services:

  postgres:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:            orthanc
      POSTGRES_PASSWORD:        ${POSTGRES_PASSWORD}
      TZ: "America/New_York"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.storage==true


  orthanc-archive:
    image: derekmerck/orthanc-confd:latest-amd64
    ports:
      - 4242:4242
    networks:
      - proxy
    environment:
      ORTHANC_AET:              CIRRARC
      ORTHANC_PASSWORD:         ${ORTHANC_PASSWORD}
      ORTHANC_PG_ENABLED:       "true"
      ORTHANC_PG_STORE_DICOM:   "true"
      ORTHANC_PG_DATABASE:      ${ORTHANC_PG_DATABASE}
      ORTHANC_PG_HOST:          postgres
      ORTHANC_PG_USER:          orthanc
      ORTHANC_PG_PASSWORD:      ${POSTGRES_PASSWORD}
      ORTHANC_VERBOSE:          "true"
      TZ:                       "America/New_York"
    depends_on:
      - postgres
    deploy:
      replicas: 1
      labels:
        - "traefik.docker.network=traefik"
        - "traefik.port=8042"
        - "traefik.frontend.rule=PathPrefixStrip:/archive/"


  orthanc-router:
    image: derekmerck/orthanc-confd:latest-amd64
    ports:
      - "5252:4242"
      - "8052:8042"
    networks:
      - proxy
    environment:
      ORTHANC_AET:              CIRRMUX
      ORTHANC_PASSWORD:         ${ORTHANC_PASSWORD}
      ORTHANC_MAX_PATIENTS:     50
      ORTHANC_ROUTE_TO_PEERS:   archive
      ORTHANC_ROUTE_TO_MODS:    workstation
      ORTHANC_PEER_0:           archive,http://orthanc-archive:8042,orthanc,${ORTHANC_PASSWORD}
      ORTHANC_MOD_0:            workstation,${MOD_WORKSTATION}
      ORTHANC_VERBOSE:         "true"
      TZ:                      "America/New_York"
    deploy:
      replicas: 1
      labels:
        - "traefik.docker.network=proxy"
        - "traefik.port=8042"
        - "traefik.frontend.rule=PathPrefixStrip:/router/"


  orthanc-bridge:
    image: derekmerck/orthanc-confd:latest-amd64
    ports:
      - "6262:4242"
      - "8062:8042"
    networks:
      - proxy
    environment:
      ORTHANC_AET:              CIRR1
      ORTHANC_PASSWORD:         ${ORTHANC_PASSWORD}
      ORTHANC_MAX_PATIENTS:     50
      ORTHANC_PEER_0:           archive,http://orthanc-archive:8042,orthanc,${ORTHANC_PASSWORD}
      ORTHANC_MOD_0:            pacs,${MOD_PACS}
      ORTHANC_VERBOSE:          "true"
      TZ:                       "America/New_York"
    deploy:
      replicas: 1
      labels:
        - "traefik.docker.network=proxy"
        - "traefik.port=8042"
        - "traefik.frontend.rule=PathPrefixStrip:/bridge/"
