version: '3.3'


networks:
  service_network:
    driver: overlay
    attachable: true

  admin_proxy_network:
    external: true   # Created by admin-stack


volumes:
  pg_data:
    driver_opts:
        type: none
        device: ${DATA_DIR}/postgres
        o: bind


services:

  postgres:
    image: postgres
    networks:
      - service_network
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:            orthanc
      POSTGRES_PASSWORD:        ${POSTGRES_PASSWORD}
      TZ: "America/New_York"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.storage==true


  orthanc-archive:
    image: derekmerck/orthanc-confd:latest-amd64
    ports:
      - 4242:4242
    networks:
      - service_network
      - admin_proxy_network
    environment:
      ORTHANC_NAME:             CIRR Archive
      ORTHANC_AET:              CIRRARC
      ORTHANC_PASSWORD:         ${ORTHANC_PASSWORD}
      ORTHANC_STORE_COMPRESSED: "true"
      ORTHANC_PG_ENABLED:       "true"
      ORTHANC_PG_STORE_DICOM:   "true"
      ORTHANC_PG_DATABASE:      ${ORTHANC_PG_DATABASE}
      ORTHANC_PG_HOST:          postgres
      ORTHANC_PG_USER:          orthanc
      ORTHANC_PG_PASSWORD:      ${POSTGRES_PASSWORD}
      ORTHANC_VERBOSE:          "true"
      TZ:                       "America/New_York"
    deploy:
      replicas: 2  # Multiple nodes, PG provides data persistence
      labels:
        - "traefik.docker.network=admin_proxy_network"
        - "traefik.port=8042"
        - "traefik.frontend.rule=PathPrefixStrip:/archive/"


  orthanc-router:
    image: derekmerck/orthanc-confd:latest-amd64
    ports:
      - "5252:4242"
      - "8052:8042"
    networks:
      - service_network
      - admin_proxy_network
    environment:
      ORTHANC_NAME:             CIRR Router
      ORTHANC_AET:              CIRRROUTER
      ORTHANC_PASSWORD:         ${ORTHANC_PASSWORD}
      ORTHANC_MAX_PATIENTS:     50
      ORTHANC_ROUTE_TO_PEERS:   archive
      ORTHANC_ROUTE_TO_MODS:    workstation
      ORTHANC_PEER_0:           archive,http://orthanc-archive:8042,orthanc,${ORTHANC_PASSWORD}
      ORTHANC_MOD_0:            workstation,${MOD_WORKSTATION}
      ORTHANC_VERBOSE:         "true"
      TZ:                      "America/New_York"
    deploy:
      replicas: 1  # Single node, semi-persistent data
      labels:
        - "traefik.docker.network=admin_proxy_network"
        - "traefik.port=8042"
        - "traefik.frontend.rule=PathPrefixStrip:/router/"


  orthanc-bridge:
    image: derekmerck/orthanc-confd:latest-amd64
    ports:
      - "6262:4242"
      - "8062:8042"
    networks:
      - service_network
      - admin_proxy_network
    environment:
      ORTHANC_NAME:             CIRR Bridge
      ORTHANC_AET:              CIRR1
      ORTHANC_PASSWORD:         ${ORTHANC_PASSWORD}
      ORTHANC_MAX_PATIENTS:     50
      ORTHANC_PEER_0:           archive,http://orthanc-archive:8042,orthanc,${ORTHANC_PASSWORD}
      ORTHANC_MOD_0:            mock,MOCK,orthanc-mock.mock,4242
      ORTHANC_MOD_1:            pacs,${MOD_PACS}
      ORTHANC_VERBOSE:          "true"
      TZ:                       "America/New_York"
    deploy:
      replicas: 1  # Single node, semi-persistent data
      labels:
        - "traefik.docker.network=admin_proxy_network"
        - "traefik.port=8042"
        - "traefik.frontend.rule=PathPrefixStrip:/bridge/"
