version: '3'

volumes:
  splunk_data:
  portainer_data:
  pg_data:
  orthanc_data:

services:

  reverse-proxy:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: "America/New_York"


  splunk:
    image: splunk/splunk
    # build:
    #   context:
    #     splunk-confd
    #   args:
    #     SPLUNK_LOGGING_TOK: ${SPLUNK_LOGGING_TOKEN}
    #     SPLUNK_REMOTES_TOK: ${SPLUNK_REMOTES_TOKEN}
    #     SPLUNK_DICOM_TOK:   ${SPLUNK_DICOM_TOKEN}
    ports:
      - "8088:8088"
      - "8089:8089"
    environment:
      SPLUNK_START_ARGS: '--accept-license --seed-passwd ${SERVICE_CREDENTIALS_PASSWORD}'
      SPLUNK_USER:  root
      TZ: "America/New_York"
    labels:
      - "traefik.port:8000"
      - "traefik.frontend.rule=PathPrefixStrip:/splunk/"


  portainer:
    image: portainer/portainer
    command: --no-auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      TZ: "America/New_York"
    labels:
      - "traefik.port=9000"
      - "traefik.frontend.redirect.regex=^(.*)/portainer$$"
      - "traefik.frontend.redirect.replacement=$$1/portainer/"
      - "traefik.frontend.rule=PathPrefix:/portainer;ReplacePathRegex: ^/portainer/(.*) /$$1"


  postgres:
    image: postgres
    volumes:
      - pg_data:/var/lib/pgsql/data
    environment:
      POSTGRES_PASSWORD: ${SERVICE_CREDENTIALS_PASSWORD}
      TZ: "America/New_York"


  redis:
    image: redis
    ports:
      - "6379:6379"


  orthanc:
    image: orthanc-confd-amd64
    ports:
      - "4242"  # Expose DICOM ingress, can't scale though
    volumes:
      - orthanc_data:/var/lib/orthanc/db
    environment:
      # ORTHANC_CONF_SOURCE:  [env (default), consul:abc, redis:abc]
      ORTHANC_REMOTE_PASSWORD: ${SERVICE_CREDENTIALS_PASSWORD}
      ORTHANC_PG_ENABLED:  "true"  # must be lowercase!
      ORTHANC_PG_DATABASE: orthanc
      ORTHANC_PG_HOST:     postgres
      ORTHANC_PG_PASSWORD: ${SERVICE_CREDENTIALS_PASSWORD}
      ORTHANC_VERBOSE:     "true"
      TZ: "America/New_York"
    labels:
      - "traefik.port=8042"
      - "traefik.frontend.rule=PathPrefixStrip:/orthanc/"





  # rabitmq:
  #   image: rabitmq


  # diana-watcher:
  #   image: derekmerck/diana
  #   command: diana-watcher


  # diana-worker:
  #   image: derekmerck/diana
  #   command: diana-worker



    # logging:
    #   driver: splunk
    #   options:
    #     splunk-token: ${SPLUNK_LOGGING_TOK}
    #     splunk-url:   ${SPLUNK_HEC_URL}

