version: '3.3'

volumes:
  pg_data:
    driver_opts:
        type: none
        device: ${DATA_DIR}/postgres/data
        o: bind


services:

  reverse-proxy:
    image: traefik
    command:
      - --api
      - --docker
      - --docker.swarmmode
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: "America/New_York"
    deploy:
      placement:
        constraints:
          - node.role==manager


  postgres:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:            orthanc
      POSTGRES_PASSWORD:        ${POSTGRES_PASSWORD}
      TZ: "America/New_York"
    deploy:
      placement:
        constraints:
          - node.labels.storage==true


  archive:
    image: derekmerck/orthanc-confd:latest-amd64
    ports:
      - 4242:4242
    environment:
      ORTHANC_PASSWORD:         ${ORTHANC_PASSWORD}
      ORTHANC_PG_ENABLED:       "true"
      ORTHANC_PG_STORE_DICOM:   "true"
      ORTHANC_PG_DATABASE:      ${ORTHANC_PG_DATABASE}
      ORTHANC_PG_HOST:          postgres
      ORTHANC_PG_USER:          orthanc
      ORTHANC_PG_PASSWORD:      ${POSTGRES_PASSWORD}
      ORTHANC_VERBOSE:          "true"
      TZ:                       "America/New_York"
    depends_on:
      - postgres
    deploy:
      replicas: 1
      labels:
        - "traefik.port=8042"
        - "traefik.frontend.rule=PathPrefixStrip:/archive/"


  router:
    image: derekmerck/orthanc-confd:latest-amd64
    ports:
      - 5252:4242
    environment:
      ORTHANC_PASSWORD:         ${ORTHANC_PASSWORD}
      ORTHANC_MAX_PATIENTS:     50

      ORTHANC_ROUTE_TO_PEERS:   orthanc
      ORTHANC_ROUTE_TO_MODS:    terarecon

      ORTHANC_PEER_0:           archive,http://orthanc:8042,orthanc,${ORTHANC_PASSWORD}
      ORTHANC_MOD_0:            TERARECON,10.200.300.10,112

      ORTHANC_VERBOSE:         "true"
      TZ:                      "America/New_York"
    deploy:
      replicas: 1
      labels:
        - "traefik.port=8042"
        - "traefik.frontend.rule=PathPrefixStrip:/router/"


  bridge:
    image: derekmerck/orthanc-confd:latest-amd64
    ports:
      - 6252:4242
    environment:
      ORTHANC_PASSWORD:         ${ORTHANC_PASSWORD}
      ORTHANC_MAX_PATIENTS:     50

      ORTHANC_PEER_0:           archive,http://orthanc:8042,orthanc,${ORTHANC_PASSWORD}
      ORTHANC_MOD_0:            RIHPACS,10.200.300.10,112

      ORTHANC_VERBOSE:         "true"
      TZ:                      "America/New_York"
    deploy:
      replicas: 1
      labels:
        - "traefik.port=8042"
        - "traefik.frontend.rule=PathPrefixStrip:/bridge/"
