version: '2'

volumes:
  portainer_data:
  pg_data:
    driver_opts:
        type: none
        device: ${DATA_DIR}/postgres/data
        o: bind
  orthanc_data:
    driver_opts:
        type: none
        device: ${DATA_DIR}/orthanc/db
        o: bind


services:

  reverse-proxy:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: "America/New_York"


  portainer:
    image: portainer/portainer
    command: --no-auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      TZ: "America/New_York"
    labels:
      - "traefik.port=9000"
      - "traefik.frontend.redirect.regex=^(.*)/portainer$$"
      - "traefik.frontend.redirect.replacement=$$1/portainer/"
      - "traefik.frontend.rule=PathPrefix:/portainer;ReplacePathRegex: ^/portainer/(.*) /$$1"


  postgres:
    image: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${SERVICE_CREDENTIALS_PASSWORD}
      TZ: "America/New_York"


  # Want to be able to scale this, so don't expose DICOM ports
  orthanc:
    image: derekmerck/orthanc-confd:latest-amd64
    volumes:
      - orthanc_data:/var/lib/orthanc/db
    environment:
      # ORTHANC_CONF_SOURCE:  [env (default), consul:abc, redis:abc]
      ORTHANC_REMOTE_PASSWORD: ${SERVICE_CREDENTIALS_PASSWORD}
      ORTHANC_PG_ENABLED:  "true"  # must be lowercase!
      ORTHANC_PG_DATABASE: ${ORTHANC_PG_DATABASE}
      ORTHANC_PG_HOST:     dstackscirr_postgres_1
      ORTHANC_PG_USER:     orthanc
      ORTHANC_PG_PASSWORD: ${POSTGRES_PASSWORD}
      ORTHANC_VERBOSE:     "true"
      TZ: "America/New_York"
    labels:
      - "traefik.port=8042"
      - "traefik.frontend.rule=PathPrefixStrip:/orthanc/"


