version: '3.3'


volumes:
  splunk_data:
    driver_opts:
        type: none
        device: ${DATA_DIR}/splunk
        o: bind


services:

  portainer:
    image: portainer/portainer
    command: --admin-password ${PORTAINER_PASSWORD}
    ports:
      - "9000:9000"
    environment:
      TZ: "America/New_York"


  splunk:
    image: splunk/splunk
    ports:
      - "8100:8000"
      - "8188:8088"
      - "8189:8089"
    volumes:
      - splunk_data:/opt/splunk/etc
    environment:
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_PASSWORD:  ${SPLUNK_PASSWORD}
      SPLUNK_HEC_TOKEN: ${SPLUNK_HEC_TOKEN}
      TZ:               "America/New_York"


  orthanc-dose:
    image: derekmerck/orthanc-confd:latest-amd64
    environment:
      ORTHANC_NAME:         Dose Reports
      ORTHANC_PASSWORD:     ${ORTHANC_PASSWORD}
      ORTHANC_MAX_PATIENTS: 50
      ORTHANC_VERBOSE:      "true"
      TZ:                   "America/New_York"


  # DIANA services and routes are complicated to config through environment vars (but it is possible).
  # It is much easier to define them through mapped service and routing yaml config files.
  diana-indexer:
    image: derekmerck/diana
    # Comment out command to idle a connected diana container for testing
    command: python3 /opt/diana/apps/cli/diana-watcher.py -s /dose_services.yml -r index_tags dose splunk
    configs:
      - dose_services.yml
    environment:
      ORTHANC_PASSWORD:     ${ORTHANC_PASSWORD}
      SPLUNK_HEC_TOKEN:     ${SPLUNK_HEC_TOKEN}
      TZ:                   "America/New_York"


configs:
  diana_services.yml:
    file: ./dose_services.yml
