version: '3.3'


networks:

  # Remove for unproxied stacks
  admin_proxy_network:
    external: true   # Created by admin-stack


services:

  orthanc-mock:
    image: derekmerck/orthanc-confd:latest-amd64
    networks:
      - default
      - admin_proxy_network
    environment:
      ORTHANC_NAME:             Mock PACS
      ORTHANC_AET:              MOCKPACS
      ORTHANC_MAX_PATIENTS:     50
      ORTHANC_PASSWORD:         ${ORTHANC_PASSWORD}
      ORTHANC_MOD_0:            cirr,CIRR1,orthanc-bridge,4242
      ORTHANC_VERBOSE:          "true"
      TZ:                       "America/New_York"
    deploy:
      replicas: 1
      labels:
        - "traefik.docker.network=admin_proxy_network"
        - "traefik.port=8042"
        - "traefik.frontend.rule=PathPrefixStrip:/mock/"


  diana-mock:
    image: derekmerck/diana
    command:                    python3 /opt/diana/apps/cli/diana-mock.py -S DIANA_SERVICES -d mock -r 30
    environment:
      DIANA_SERVICES: >
                                {
                                  "mock": {"host": "orthanc-mock",
                                           "password": "${ORTHANC_PASSWORD}" }
                                }
      TZ:                       "America/New_York"
    deploy:
      replicas: 1
