version: '3.3'


networks:
  cirr_service_network:
    external: true   # Created by cirr-stack

  admin_proxy_network:
    external: true   # Created by admin-stack


services:

  orthanc-wbv:
    image: derekmerck/orthanc-wbv:latest-amd64
    networks:
      - cirr_service_network
      - admin_proxy_network
    environment:
      ORTHANC_NAME:             CIRR Supplemental Review
      ORTHANC_PASSWORD:         ${ORTHANC_PASSWORD}
      ORTHANC_STORE_COMPRESSED: "true"
      ORTHANC_WBV_ENABLED:      "true"
      ORTHANC_PG_ENABLED:       "true"
      ORTHANC_PG_STORE_DICOM:   "true"
      ORTHANC_PG_DATABASE:      wbv1
      ORTHANC_PG_HOST:          postgres
      ORTHANC_PG_USER:          orthanc
      ORTHANC_PG_PASSWORD:      ${POSTGRES_PASSWORD}
      ORTHANC_VERBOSE:          "true"
      TZ:                       "America/New_York"
    deploy:
      replicas: 1  # PG provides data persistence
      labels:
        - "traefik.docker.network=admin_proxy_network"
        - "traefik.port=8042"
        - "traefik.frontend.rule=PathPrefixStrip:/wbv/"
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.2'
          memory: 100M


  diana-indexer:
    image: derekmerck/diana
    # command: python3 /opt/diana/apps/cli/diana-watcher.py -S DIANA_SERVICES -r proxied_index mock splunk
    # command: python3 /opt/diana/apps/cli/diana-watcher.py -s /diana_services.yml -r proxied_index mock-studies splunk --dump
    networks:
      - cirr_service_network    # for orthanc-bridge
      - admin_proxy_network     # for splunk
    configs:
      - diana_services.yml
    environment:
      ORTHANC_PASSWORD:         ${ORTHANC_PASSWORD}
      SPLUNK_HEC_TOKEN:         ${SPLUNK_HEC_TOKEN}
#      DIANA_SERVICES: >
#        {"mock":{"host":"orthanc-bridge","password":"${ORTHANC_PASSWORD}","query_dict":{"ModalitiesInStudy":"","StudyDescription":"*"},"query_domain":"mock","query_level":1,"query_discovery_period":300,"polling_interval":120},"splunk":{"host":"splunk","default_index":"dicom","default_token":"watcher","hec_tokens":{"watcher":"${SPLUNK_HEC_TOKEN}"}}}
      TZ:                       "America/New_York"
    deploy:
      replicas: 1

configs:
  diana_services.yml:
    file: ./diana_services.yml
