version: '3.3'


networks:
  cirr_service_network:
    external: true   # Created by cirr-stack

  admin_proxy_network:
    external: true   # Created by admin-stack


services:

  orthanc-wbv:
    image: derekmerck/orthanc-wbv:latest-amd64
    networks:
      - cirr_service_network
      - admin_proxy_network
    environment:
      ORTHANC_NAME:             CIRR Supplemental Review
      ORTHANC_PASSWORD:         ${ORTHANC_PASSWORD}
      ORTHANC_STORE_COMPRESSED: "true"
      ORTHANC_WBV_ENABLED:      "true"
      ORTHANC_PG_ENABLED:       "true"
      ORTHANC_PG_STORE_DICOM:   "true"
      ORTHANC_PG_DATABASE:      wbv1
      ORTHANC_PG_HOST:          postgres
      ORTHANC_PG_USER:          orthanc
      ORTHANC_PG_PASSWORD:      ${POSTGRES_PASSWORD}
      ORTHANC_VERBOSE:          "true"
      TZ:                       "America/New_York"
    deploy:
      replicas: 1  # PG provides data persistence
      labels:
        - "traefik.docker.network=admin_proxy_network"
        - "traefik.port=8042"
        - "traefik.frontend.rule=PathPrefixStrip:/wbv/"

