version: '2'


services:

  archive-queue:
    image: derekmerck/orthanc-confd:latest-amd64
    environment:
      ORTHANC_REMOTE_PASSWORD: ${ORTHANC_PASSWORD}
      ORTHANC_MAX_PATIENTS:    100

      ORTHANC_PEERDEST_0:      cirr1

      ORHTANC_PEERS_0_ADDR:    http://orthanc:${ORTHANC_PASSWORD}@cirr1/orthanc/

      ORTHANC_VERBOSE:         "true"
      TZ: "America/New_York"
    labels:
      - "traefik.port=8042"
      - "traefik.frontend.rule=PathPrefixStrip:/archive-queue/"


  terarecon-mux:
    image: derekmerck/orthanc-confd:latest-amd64
    environment:
      ORTHANC_REMOTE_PASSWORD:  ${ORTHANC_PASSWORD}
      ORTHANC_MAX_PATIENTS:     100

      ORTHANC_PEER_DEST0:      cirr1
      ORTHANC_MOD_DEST0:       terarecon

      ORTHANC_PEERS0_NAME:     cirr1
      ORHTANC_PEERS0_ADDR:     http://orthanc:${ORTHANC_PASSWORD}@cirr1/orthanc/

      ORTHANC_MOD0_NAME:       terarecon
      ORHTANC_MOD0_ADDR:       dcm:TERARECON@10.200.300.10:4242


      ORTHANC_VERBOSE:         "true"
      TZ: "America/New_York"
    labels:
      - "traefik.port=8042"
      - "traefik.frontend.rule=PathPrefixStrip:/terarecon-mux/"