---
- source:  incoming-hobit
  event:   NEW_FILE
  handler: move
  dest:    orthanc-hobit

- source:  orthanc-hobit-queue
  event:   STABLE_STUDY
  handler: move
  args:    anon=true
  dest:    orthanc-hobit

- source:  orthanc-hobit
  event:   STABLE_STUDY
  handler: index
  dest:    splunk
