version: '3.3'


networks:
  proxy_network:
    driver: overlay
    attachable: true

  agent_network:
    driver: overlay
    attachable: true


volumes:
  splunk_data:
    driver_opts:
        type: none
        device: ${DATA_DIR}/splunk
        o: bind


services:

  portainer-agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.portainer-agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - agent_network
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]

  portainer:
    image: portainer/portainer
    command: -H tcp://tasks.portainer-agent:9001 --tlsskipverify --admin-password ${PORTAINER_PASSWORD}
    ports:
      - "9000:9000"
    networks:
      - proxy_network
      - agent_network
    environment:
      TZ: "America/New_York"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
      labels:
        - "traefik.docker.network=cirr_proxy_network"
        - "traefik.port=9000"
        - "traefik.frontend.rule=PathPrefixStrip:/portainer/"

  traefik:
    image: traefik
    command:
      - --api
      - --docker
      - --docker.swarmmode
    ports:
      - "80:80"
      - "433:433"
      - "8080:8080"
    networks:
      - proxy_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TZ: "America/New_York"
    deploy:
      placement:
        constraints:
          - node.role==manager

  splunk:
    image: splunk/splunk
    ports:
      - "8100:8000"
      - "8188:8088"
      - "8189:8089"
    networks:
      - proxy_network
    volumes:
      - splunk_data:/opt/splunk/etc
    environment:
      SPLUNK_START_ARGS: "--accept-license"
      SPLUNK_PASSWORD:  ${SPLUNK_PASSWORD}
      SPLUNK_HEC_TOKEN: ${SPLUNK_HEC_TOKEN}
      TZ: "America/New_York"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.storage==true
      labels:
        - "traefik.docker.network=cirr_proxy_network"
        - "traefik.port=8000"
        - "traefik.frontend.rule=PathPrefixStrip:/splunk/"
      resources:
        limits:
          cpus:   '2'
          memory: 4G
        reservations:
          cpus: '0.5'
          memory: 2G
