version: '3.3'


networks:
  cirr_service_network:
    external: true   # Created by cirr-stack

  admin_proxy_network:
    external: true   # Created by admin-stack


services:

  orthanc-review-01:
    image: derekmerck/orthanc-wbv:latest-amd64
    networks:
      - cirr_service_network
      - admin_proxy_network
    environment:
      ORTHANC_NAME:             CIRR Supplemental Review 1
      ORTHANC_PASSWORD:         ${ORTHANC_PASSWORD}
      ORTHANC_STORE_COMPRESSED: "true"
      ORTHANC_WBV_ENABLED:      "true"
      ORTHANC_PG_ENABLED:       "true"
      ORTHANC_PG_STORE_DICOM:   "true"
      ORTHANC_PG_DATABASE:      review01
      ORTHANC_PG_HOST:          postgres
      ORTHANC_PG_USER:          orthanc
      ORTHANC_PG_PASSWORD:      ${POSTGRES_PASSWORD}
      ORTHANC_VERBOSE:          "true"
      TZ:                       "America/New_York"
    deploy:
      replicas: 1  # PG provides data persistence
      labels:
        - "traefik.docker.network=admin_proxy_network"
        - "traefik.port=8042"
        - "traefik.frontend.rule=PathPrefixStrip:/review01/"
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
        reservations:
          cpus: '0.2'
          memory: 100M

  # DIANA services and routes are complicated to config through environment vars (but it is possible).
  # It is much easier to define them through mapped service and routing yaml config files.
  diana-indexer:
    image: derekmerck/diana
    # Comment out command to idle a connected diana container for testing
    # command: python3 /opt/diana/apps/cli/diana-cli.py -S /services.yml watch -C /routes.yml
    networks:
      - cirr_service_network    # for orthanc-bridge
      - admin_proxy_network     # for splunk
    configs:
      - source: diana_services_01
        target: /services.yml
      - source: diana_routes_01
        target: /routes.yml
    environment:
      ORTHANC_PASSWORD:         ${ORTHANC_PASSWORD}
      SPLUNK_HEC_TOKEN:         ${SPLUNK_HEC_TOKEN}
      TZ:                       "America/New_York"
    deploy:
      replicas: 1


configs:
  diana_services_01:
    file: ./diana_services.yml
  diana_routes_01:
    file: ./diana_routes.yml
