debug = false
insecureSkipVerify = true

logLevel = "DEBUG"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
#    [entryPoints.http.redirect]
#    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "central-imaging.com"
watch = true
# exposedByDefault = false

[acme]
email = "admin@central-imaging.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true

# Staging
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"

[acme.httpChallenge]
entryPoint = "http"